name: lbCon BE CI/CD Action

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 프로젝트를 원격 서버에 SSH 배포
      - name: Remote Access Deployment for pm2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SSH_HOST }} 
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git pull
            npm ci
            pm2 reload ecosystem.config.js --max-memory-restart 1.9G
