name: lbCon BE CI/CD Action

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

    steps:
      # 프로젝트를 원격 서버에 SSH 배포
      - name: Remote Access Deployment for pm2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets[format('AWS_SSH_HOST_{0}', matrix.instance)] }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd backend
            git pull
            npm i aws-sdk
            npm ci
            pm2 reload ecosystem.config.js --max-memory-restart 1.9G
